/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.starrocks.connector.thrift;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2022-10-12")
public enum TAggregationType implements org.apache.thrift.TEnum {
  SUM(0),
  MAX(1),
  MIN(2),
  REPLACE(3),
  HLL_UNION(4),
  NONE(5);

  private final int value;

  private TAggregationType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static TAggregationType findByValue(int value) { 
    switch (value) {
      case 0:
        return SUM;
      case 1:
        return MAX;
      case 2:
        return MIN;
      case 3:
        return REPLACE;
      case 4:
        return HLL_UNION;
      case 5:
        return NONE;
      default:
        return null;
    }
  }
}
